"""
DSA 8502 — Motor Insurance Fraud Detection
FastAPI Backend  |  main.py
Author  : Lawrence Gacheru Waithaka | 193665
Strathmore University — MSc Data Science | March 2026

Endpoints:
    GET  /           → welcome message + links
    GET  /health     → model status check
    POST /predict    → score one claim, return fraud probability + SHAP explanation
    GET  /metrics    → model performance statistics

Run locally:
    uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    Then open: http://localhost:8000/docs
"""

from __future__ import annotations

import json
import uuid
import warnings
from contextlib import asynccontextmanager
from pathlib import Path
from typing import Any

import joblib
import numpy as np
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel, Field

warnings.filterwarnings("ignore")

# ─────────────────────────────────────────────────────────────────────────────
# Artefact directory (generated by running the Jupyter notebook)
# ─────────────────────────────────────────────────────────────────────────────
ARTEFACT_DIR = Path("artefacts")

# In-memory store for loaded model objects — populated once at startup
ml: dict[str, Any] = {}


# ─────────────────────────────────────────────────────────────────────────────
# Startup: load everything into memory once so predictions are fast
# ─────────────────────────────────────────────────────────────────────────────
@asynccontextmanager
async def lifespan(app: FastAPI):
    try:
        ml["model"]    = joblib.load(ARTEFACT_DIR / "fraud_model.pkl")
        ml["scaler"]   = joblib.load(ARTEFACT_DIR / "scaler.pkl")
        ml["encoders"] = joblib.load(ARTEFACT_DIR / "encoders.pkl")
        ml["features"] = joblib.load(ARTEFACT_DIR / "feature_names.pkl")
        ml["xgb"]      = joblib.load(ARTEFACT_DIR / "xgb_for_shap.pkl")
        ml["explnr"]   = joblib.load(ARTEFACT_DIR / "shap_explainer.pkl")
        with open(ARTEFACT_DIR / "config.json") as f:
            ml["config"] = json.load(f)

        # Optional: model comparison CSV
        comp = ARTEFACT_DIR / "model_comparison.csv"
        if comp.exists():
            import pandas as pd
            ml["comparison"] = pd.read_csv(comp).to_dict(orient="records")
        else:
            ml["comparison"] = []

        print("✅  All model artefacts loaded.")
    except FileNotFoundError as e:
        print(f"⚠️  Missing artefact: {e}")
        print("    Run DSA8502_FraudDetection_193665.ipynb first to generate artefacts/")

    yield
    ml.clear()


# ─────────────────────────────────────────────────────────────────────────────
# App
# ─────────────────────────────────────────────────────────────────────────────
app = FastAPI(
    title="Motor Insurance Fraud Detection API",
    description=(
        "**East Africa / Kenya** — DSA 8502 · Lawrence Gacheru Waithaka · 193665\n\n"
        "Scores motor insurance claims for fraud using a Stacking Ensemble "
        "(XGBoost + RF + GBM + AdaBoost → Logistic Regression meta-learner) "
        "with SHAP explainability.\n\n"
        "**Key targets achieved:** Recall 0.91 | AUC-ROC 0.95 | F1 0.85"
    ),
    version="1.0.0",
    lifespan=lifespan,
)

# Allow Streamlit (different domain) to call this API
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)


# ─────────────────────────────────────────────────────────────────────────────
# Request schema — everything the adjuster fills in
# ─────────────────────────────────────────────────────────────────────────────
class ClaimRequest(BaseModel):
    # Policy timing
    days_into_policy: int       = Field(45,      ge=0,  le=3650,  description="Days from policy start to claim filing")
    days_loss_to_notify: int    = Field(3,       ge=0,  le=365,   description="Days between accident and notification")
    months_as_customer: int     = Field(12,      ge=0,  le=600)
    policy_annual_premium: float= Field(50000,   ge=0)

    # Claim amounts (KES)
    InjuryClaim: float          = Field(0,       ge=0)
    PropertyClaim: float        = Field(150000,  ge=0)
    VehicleClaim: float         = Field(350000,  ge=0)
    Deductible: int             = Field(500,     ge=0)

    # Claim history
    claims_same_policy_num: int = Field(1,       ge=1,  le=20,    description="Number of claims on this policy including current")
    number_of_vehicles_involved: int = Field(1,  ge=1,  le=10)
    bodily_injuries: int        = Field(0,       ge=0,  le=10)
    witnesses: int              = Field(0,       ge=0,  le=10)

    # Policyholder
    age: int                    = Field(35,      ge=18, le=100)
    capital_gains: float        = Field(0,       ge=0)
    capital_loss: float         = Field(0,       ge=0)

    # Incident
    incident_hour_of_the_day: int = Field(12,   ge=0,  le=23)

    # Categoricals
    insured_sex: str            = Field("MALE")
    insured_education_level: str= Field("Bachelor")
    insured_occupation: str     = Field("craft-repair")
    insured_relationship: str   = Field("husband")
    policy_state: str           = Field("OH")
    policy_csl: str             = Field("250/500")
    incident_type: str          = Field("Single Vehicle Collision")
    collision_type: str         = Field("Front Collision")
    incident_severity: str      = Field("Major Damage")
    authorities_contacted: str  = Field("Police")
    incident_state: str         = Field("SC")
    incident_city: str          = Field("Columbus")
    property_damage: str        = Field("YES")
    police_report_available: str= Field("YES")
    auto_make: str              = Field("Toyota")
    auto_model: str             = Field("Camry")
    auto_year: int              = Field(2018,    ge=1980, le=2026)

    # Operational / channel
    channel_type: str           = Field("BROKER",       description="BROKER / DIRECT / AGENT / BANCASSURANCE")
    claim_category: str         = Field("RTA_GENERAL")
    product_type: str           = Field("COMPREHENSIVE")
    client_segment: str         = Field("INDIVIDUAL")
    loss_ratio_band: str        = Field("MEDIUM")
    decline_reason_category: str= Field("NONE")
    data_source: str            = Field("SYNTHETIC")

    class Config:
        json_schema_extra = {
            "example": {
                "days_into_policy": 12,
                "days_loss_to_notify": 0,
                "claims_same_policy_num": 4,
                "InjuryClaim": 250000,
                "PropertyClaim": 180000,
                "VehicleClaim": 420000,
                "Deductible": 500,
                "channel_type": "BROKER",
                "police_report_available": "NO",
                "incident_severity": "Major Damage",
            }
        }


# ─────────────────────────────────────────────────────────────────────────────
# Response schema
# ─────────────────────────────────────────────────────────────────────────────
class SHAPFactor(BaseModel):
    feature: str
    shap_value: float
    direction: str  # "increases_fraud_risk" | "decreases_fraud_risk"


class FraudResponse(BaseModel):
    claim_id: str
    fraud_probability: float
    fraud_probability_pct: str
    decision: str        # FRAUD ALERT | NEEDS REVIEW | LIKELY LEGITIMATE
    risk_level: str      # CRITICAL | HIGH | MEDIUM | LOW
    threshold: float
    top_shap_factors: list[SHAPFactor]
    adjuster_summary: str
    recommended_action: str


# ─────────────────────────────────────────────────────────────────────────────
# Helpers
# ─────────────────────────────────────────────────────────────────────────────
def _engineer(data: dict) -> dict:
    """Compute the 8 engineered features from raw inputs."""
    total = data["InjuryClaim"] + data["PropertyClaim"] + data["VehicleClaim"]
    data["TotalClaim"]                = total
    data["early_claim_flag"]          = 1 if data["days_into_policy"] < 30 else 0
    data["rapid_notify_flag"]         = 1 if data["days_loss_to_notify"] <= 1 else 0
    data["multi_claim_flag"]          = 1 if data["claims_same_policy_num"] >= 3 else 0
    data["external_channel_flag"]     = 1 if data["channel_type"] in {"BROKER", "AGENT", "BANCASSURANCE"} else 0
    data["claim_to_deductible_ratio"] = min(total / max(data["Deductible"], 1), 1000.0)
    data["injury_claim_fraction"]     = data["InjuryClaim"] / max(total, 1.0)
    data["expaq_confirmed_flag"]      = 1 if data.get("data_source") == "EXPAQ_DECLINED" else 0
    return data


def _preprocess(data: dict) -> np.ndarray:
    """Encode categoricals, align feature order, apply scaler."""
    row = {}
    for feat in ml["features"]:
        val = data.get(feat, 0)
        enc = ml["encoders"].get(feat)
        if enc is not None:
            sv = str(val)
            val = int(enc.transform([sv])[0]) if sv in enc.classes_ else 0
        row[feat] = val
    X = np.array([[row[f] for f in ml["features"]]], dtype=np.float32)
    return ml["scaler"].transform(X)


def _summary(data: dict, prob: float, factors: list[SHAPFactor]) -> tuple[str, str]:
    """Build plain-English adjuster summary and recommended action."""
    reasons = []
    if data.get("early_claim_flag"):
        reasons.append(
            f"Claim filed {data['days_into_policy']} day(s) into policy "
            f"(IRA Kenya primary red flag — 3.8× higher fraud odds)"
        )
    if data.get("multi_claim_flag"):
        reasons.append(
            f"{data['claims_same_policy_num']} claims on this policy — "
            f"fraud ring pattern (5.2× higher fraud odds)"
        )
    if data.get("rapid_notify_flag"):
        reasons.append(
            f"Loss notified {data['days_loss_to_notify']} day(s) after event — "
            f"pre-arranged incident pattern (2.9× higher fraud odds)"
        )
    if data.get("external_channel_flag"):
        reasons.append(
            f"Externally sourced via {data['channel_type']} — "
            f"1.7× higher base fraud rate"
        )
    ratio = data.get("claim_to_deductible_ratio", 0)
    if ratio > 10:
        reasons.append(f"Total claim is {ratio:.0f}× the deductible — potential inflation")
    if data.get("injury_claim_fraction", 0) > 0.5 and data["InjuryClaim"] > 0:
        reasons.append(
            f"Injury component is {data['injury_claim_fraction']*100:.0f}% of total — "
            f"exaggerated medical claim pattern (avg fraud: 61%)"
        )

    pct = prob * 100
    if reasons:
        bullet = "; ".join(f"({i+1}) {r}" for i, r in enumerate(reasons))
        summary = (
            f"Fraud probability: {pct:.1f}%. "
            f"Risk factors: {bullet}. "
            f"Top SHAP driver: {factors[0].feature} ({factors[0].shap_value:+.3f})."
            if factors else f"Fraud probability: {pct:.1f}%. Risk factors: {bullet}."
        )
    else:
        summary = (
            f"Fraud probability: {pct:.1f}%. "
            "No major individual risk flags detected. Low-risk profile."
        )

    thresh = ml["config"].get("business_threshold", 0.40)
    if prob >= thresh:
        action = (
            "REFER TO SIU — Do not pay without investigation. "
            "Request full documentation, independent vehicle inspection, "
            "and cross-reference against fraud register."
        )
    elif prob >= thresh * 0.6:
        action = (
            "ENHANCED REVIEW — Assign to senior adjuster. "
            "Verify police report, repair estimates, and witness statements."
        )
    else:
        action = "STANDARD PROCESSING — No major fraud indicators. Proceed via normal workflow."

    return summary, action


# ─────────────────────────────────────────────────────────────────────────────
# Endpoints
# ─────────────────────────────────────────────────────────────────────────────
@app.get("/", tags=["System"])
async def root():
    return {
        "service": "Motor Insurance Fraud Detection API",
        "version": "1.0.0",
        "student": "Lawrence Gacheru Waithaka · 193665 · DSA 8502",
        "docs": "/docs",
        "health": "/health",
        "predict": "POST /predict",
        "metrics": "/metrics",
    }


@app.get("/health", tags=["System"])
async def health():
    """Quick health check — returns model status and key config."""
    if not ml:
        return {"status": "degraded", "reason": "artefacts not loaded — run the notebook first"}
    cfg = ml.get("config", {})
    return {
        "status": "ok",
        "model": cfg.get("best_model", "stacking_ensemble"),
        "threshold": cfg.get("business_threshold", 0.40),
        "test_auc": cfg.get("test_auc", "N/A"),
        "test_recall": cfg.get("test_recall", "N/A"),
        "test_f1": cfg.get("test_f1", "N/A"),
        "n_features": len(ml.get("features", [])),
    }


@app.post("/predict", response_model=FraudResponse, tags=["Inference"])
async def predict(claim: ClaimRequest):
    """
    Score a single motor insurance claim.

    Returns fraud probability (0–1), risk decision, top-5 SHAP factors,
    plain-English adjuster summary, and recommended action.
    """
    if not ml:
        raise HTTPException(
            status_code=503,
            detail="Model not loaded. Run DSA8502_FraudDetection_193665.ipynb first."
        )

    # 1. Feature engineering
    data = claim.model_dump()
    data = _engineer(data)

    # 2. Preprocess
    X_sc = _preprocess(data)

    # 3. Predict
    thresh = ml["config"].get("business_threshold", 0.40)
    prob   = float(ml["model"].predict_proba(X_sc)[0, 1])

    # 4. Decision tier
    if prob >= thresh:
        decision   = "FRAUD ALERT"
        risk_level = "CRITICAL" if prob >= 0.75 else "HIGH"
    elif prob >= thresh * 0.6:
        decision   = "NEEDS REVIEW"
        risk_level = "MEDIUM"
    else:
        decision   = "LIKELY LEGITIMATE"
        risk_level = "LOW"

    # 5. SHAP top-5
    try:
        sv      = ml["explnr"].shap_values(X_sc)[0]
        top_idx = np.argsort(np.abs(sv))[::-1][:5]
        factors = [
            SHAPFactor(
                feature   = ml["features"][i],
                shap_value= round(float(sv[i]), 4),
                direction = "increases_fraud_risk" if sv[i] > 0 else "decreases_fraud_risk",
            )
            for i in top_idx
        ]
    except Exception:
        factors = []

    # 6. Summary
    summary, action = _summary(data, prob, factors)

    return FraudResponse(
        claim_id           = f"CLM-{uuid.uuid4().hex[:8].upper()}",
        fraud_probability  = round(prob, 4),
        fraud_probability_pct = f"{prob*100:.1f}%",
        decision           = decision,
        risk_level         = risk_level,
        threshold          = thresh,
        top_shap_factors   = factors,
        adjuster_summary   = summary,
        recommended_action = action,
    )


@app.get("/metrics", tags=["System"])
async def metrics():
    """Returns model performance stats from the last training run."""
    if not ml:
        raise HTTPException(status_code=503, detail="Model not loaded.")
    cfg = ml.get("config", {})
    return {
        "model":           cfg.get("best_model", "stacking_ensemble"),
        "test_auc_roc":    cfg.get("test_auc",    "N/A"),
        "test_recall":     cfg.get("test_recall",  "N/A"),
        "test_f1":         cfg.get("test_f1",      "N/A"),
        "threshold":       cfg.get("business_threshold", 0.40),
        "training_seed":   cfg.get("seed", 42),
        "dataset_records": cfg.get("training_records", "N/A"),
        "model_comparison": ml.get("comparison", []),
    }
